### ISSUE TITLE
Configuration Management and Quality Management - 15th December

### ISSUE THREAD

**Issue by CarlosAlmRom** [CarlosAlmRom/ISO2-2022-A05#27]
@fluctlights have to upload the Configuration Management and Quality Management wiki.

**Comment by fluctlights** [comment]
Uploaded Configuration Management:  https://github.com/CarlosAlmRom/ISO2-2022-A05/wiki/Configuration-Management

Also uploaded Quality Management wiki:  https://github.com/CarlosAlmRom/ISO2-2022-A05/wiki/Quality-Management
